name: automerge
on:
  workflow_dispatch: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: false
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
